APP_VERSION = "0.2.2"
COLLECTOR_VERSION = "0.2.1"
PROMPT_VERSION = "personal-chats-digest-v2"
STATUS_REQUEST_SCHEMA = "sunny.personal-chats.status-request.v2"
GATE_SCHEMA = "sunny.personal-chats.status-gate.v2"
MONITOR_UPLOAD_SCHEMA = "sunny.personal-chats.monitor.v2"
DIGEST_UPLOAD_SCHEMA = "sunny.personal-chats.digest.v2"
RECEIPT_SCHEMA = "sunny.personal-chats.receipt.v2"
MAX_UPLOAD_BYTES = 32 * 1024
MAX_PROMPT_BYTES = 96 * 1024
MAX_DIGEST_CHARS = 3_700
MAX_SCAN_MESSAGES = 1_000
MAX_SELECTED_CHATS = 16
MAX_MENTION_EVENTS = 10
MAX_MENTION_SNIPPET_UTF16 = 300
DEFAULT_LOOKBACK_HOURS = 72
